UI/WebSite/Controllers/TerminalController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MgmtForm.BL.Interfaces;
using MgmtForm.Utility.Extensions;
using MgmtForm.ViewModels;
using Newtonsoft.Json;

namespace MgmtForm.UI.Controllers
{
    public class TerminalController : Controller
    {

        //
        // GET: /Company/
        public ActionResult Index()
        {
            return View();
        }


        public ActionResult InvokePowerShell(FormCollection formdata)
        {
            if (string.IsNullOrEmpty(formdata["cmd"]))
            {
                throw new Exception("缺少cmd參數");
            }

            PowerShellCommand powerShellCommand = new PowerShellCommand();
            var cmdResponse = "";
            try
            {
                cmdResponse = powerShellCommand.Exec(formdata["cmd"]);
            }
            catch (Exception ex)
            {
                cmdResponse = ex.Message;
            }
            return Json(new
            {
                response = cmdResponse
            });
        }


    }
}

UI/WebSite/Views/Terminal/Index.cshtml
@{
    ViewBag.Title = "Terminal 服務管理";
}


<div class="terminal">
    @if (TempData["command_request"] != null)
    {
        <div class="terminal-output">執行> @TempData["command_request"].ToString()</div>
        <br>
        <div class="terminal-output text-danger">結果> </div>
        foreach (string line in TempData["command_response"].ToString().Split(new string[] { "\r\n" }, StringSplitOptions.RemoveEmptyEntries))
        {
            <div class="text-danger">@line</div>
        }
        <br>
    }
</div>



@section scripts {
    <script>
        jQuery(function ($, undefined) {
            $('.terminal').terminal(function (command, term) {
                if (command !== '') {
                    $.ajax({
                        type: "POST",
                        url: "@Url.Action("InvokePowerShell", "Terminal")",
                        async: false,
                        data: {
                            cmd: command
                        },
                        beforeSend: function() {
                            term.pause();
                        },
                        success: function (e) {
                            if (e.response == '') {
                                term.error(new String("不合法的命令"));
                            }
                            term.echo(new String(e.response));
                            term.resume();
                        }
                    });
                } else {
                    term.echo('');
                }
            }, {
                greetings: false,
                name: 'js_demo',
                height: 400,
                prompt: '> '
            });
        });
    </script>
}